export interface SkillDetail {
  slug: string;
  name: string;
  nameEn: string;
  type: "original" | "enhanced";
  category: string;
  description: string;
  lines: number;
  safetyScore: number;
  grade: string;
  installCmd: string;
  upstream?: string;
  features: string[];
  useCases: string[];
  triggerWords: string[];
  skillMdPreview: string; // 核心内容摘要
}

export const allSkills: SkillDetail[] = [
  {
    slug: "xiaohongshu", name: "小红书", nameEn: "xiaohongshu", type: "original", category: "内容创作",
    lines: 239, safetyScore: 85, grade: "A",
    installCmd: "npx skills add mindverse/skillhub@xiaohongshu -g -y",
    description: "小红书内容创作助手，支持种草笔记、好物推荐、教程干货、探店测评、穿搭分享、旅行攻略等多种内容类型。写出来像真人发的，不像 AI。",
    features: ["6种内容类型", "标题公式（6种爆款模板）", "标签策略（精准/场景/流量三层）", "排版优化（手机端适配）", "口语化检查"],
    useCases: ["写一篇面霜种草笔记", "帮我写个探店测评", "小红书标题怎么起", "这篇笔记帮我排版一下"],
    triggerWords: ["小红书", "种草", "笔记", "好物推荐", "探店", "xhs", "RED note"],
    skillMdPreview: "# 小红书 — 内容创作助手\n\n你是一位资深小红书博主，写出的每一篇笔记都像是真人亲手写的。\n\n## 工作流程\n1. 分析需求（不过度追问，最多问2个关键问题）\n2. 确定风格（种草/教程/探店/穿搭/旅行/好物推荐/干货）\n3. 撰写正文（钩子开头 + 正文主体 + 互动结尾）\n4. 生成标题（6种爆款公式）\n5. 添加标签（精准+场景+流量三层策略）\n6. 排版优化（emoji + 短段落 + 手机端适配）\n\n## 能力边界\n生成配图 → 技能宝可以帮你找到配图技能",
  },
  {
    slug: "frontend-design", name: "前端美化", nameEn: "frontend-design", type: "enhanced", category: "开发工具",
    lines: 242, safetyScore: 83, grade: "B", upstream: "anthropics/skills",
    installCmd: "npx skills add mindverse/skillhub@frontend-design -g -y",
    description: "前端界面美化助手，拒绝千篇一律的 AI 审美。颜色搭配、排版优化、响应式布局、动效建议、组件美化、暗色模式，输出生产级代码。",
    features: ["反AI审美（禁止紫色渐变白底）", "中文字体推荐", "2026设计趋势", "暗色模式", "Tailwind/CSS/React 输出", "响应式布局"],
    useCases: ["帮我美化这个页面", "界面太丑了怎么办", "给我一个配色方案", "做个暗色模式"],
    triggerWords: ["前端美化", "UI优化", "界面美化", "帮我美化", "太丑了", "frontend design"],
    skillMdPreview: "# 前端美化 — UI/UX 增强\n\n基于 Anthropic 官方 frontend-design 技能增强。\n\n## 六大能力\n1. 颜色搭配（oklch色彩空间）\n2. 排版优化（中文行高 1.8-2.0）\n3. 响应式布局（Container Queries）\n4. 动效建议（View Transitions API）\n5. 组件美化\n6. 暗色模式\n\n## 中文增强\n- 思源宋体/黑体、霞鹜文楷、阿里巴巴普惠体\n- 中文排版参数\n- 新增中式雅韵风格方向",
  },
  {
    slug: "web-design", name: "设计大师", nameEn: "web-design", type: "enhanced", category: "设计",
    lines: 642, safetyScore: 95, grade: "S", upstream: "vercel-labs/agent-skills",
    installCmd: "npx skills add mindverse/skillhub@web-design -g -y",
    description: "网站设计与 UI 设计指导，642行完整设计系统。覆盖布局设计、配色方案、字体选择、间距系统、组件设计、无障碍合规。",
    features: ["完整设计Token", "配色方案（Primary→Surface全套）", "中文字体系统", "间距系统（4px基数）", "无障碍检查清单", "Tailwind v3/v4 输出"],
    useCases: ["设计一个网站", "给我一套设计系统", "配色方案怎么选", "间距规范是什么"],
    triggerWords: ["设计大师", "网页设计", "UI设计", "设计系统", "配色", "web design", "design system"],
    skillMdPreview: "# 设计大师 — Web 设计系统\n\n基于 Vercel Labs web-design-guidelines（13.7万安装）增强。\n\n## 八大模块\n1. 布局设计原则（栅格+响应式断点）\n2. 配色方案（品牌→色阶推导）\n3. 字体选择（中英文搭配推荐）\n4. 间距系统（4px基数，0-128px Token）\n5. 组件设计（按钮/表单/卡片）\n6. 设计系统架构（Token→组件→模板四层）\n7. 无障碍合规检查\n8. 工作流程\n\n输出：CSS变量 / Tailwind v4 / Tailwind v3",
  },
  {
    slug: "brainstorming", name: "头脑风暴", nameEn: "brainstorming", type: "enhanced", category: "效率工具",
    lines: 271, safetyScore: 88, grade: "A",
    installCmd: "npx skills add mindverse/skillhub@brainstorming -g -y",
    description: "创意发散与方案构思助手，支持6种思维框架，从发散到收敛再到可行性评估，输出可操作的行动方案。",
    features: ["SCAMPER", "六顶思考帽", "5W1H", "SWOT", "逆向思维", "类比思维", "可行性评估矩阵"],
    useCases: ["帮我想点子", "这个方案怎么优化", "创意讨论一下", "头脑风暴"],
    triggerWords: ["头脑风暴", "想点子", "创意讨论", "方案构思", "brainstorm", "ideation"],
    skillMdPreview: "# 头脑风暴 — 创意发散引导师\n\n## 五阶段工作流\n1. 定义问题（一句话问题陈述）\n2. 发散思维（6种框架任选）\n3. 结构化整理（分类+优先级）\n4. 可行性评估（1-5分多维打分）\n5. 行动方案（具体步骤+责任人+时间）\n\n## 六种框架\nSCAMPER / 六顶思考帽 / 5W1H / SWOT / 逆向思维 / 类比思维",
  },
  {
    slug: "ppt-master", name: "PPT大师", nameEn: "ppt-master", type: "enhanced", category: "效率工具",
    lines: 535, safetyScore: 85, grade: "A",
    installCmd: "npx skills add mindverse/skillhub@ppt-master -g -y",
    description: "Reveal.js 演示文稿制作大师，生成可直接在浏览器打开的 HTML 幻灯片。15套配色，支持代码高亮、渐进动画、演讲者备注。",
    features: ["15套配色方案", "单文件HTML输出", "代码高亮", "渐进动画", "演讲者备注", "中文排版优化"],
    useCases: ["做个PPT", "帮我做演示文稿", "汇报材料", "技术分享的slides"],
    triggerWords: ["PPT", "演示文稿", "幻灯片", "slides", "presentation", "做个PPT"],
    skillMdPreview: "# PPT大师 — Reveal.js 演示文稿\n\n## 工作流\n1. 理解主题 & 设计构思\n2. 设计大纲\n3. 生成 HTML（CDN加载Reveal.js）\n4. 填充内容（多栏布局/动画/代码高亮）\n5. 排版美化（中文字体/内容溢出检查）\n6. 输出HTML文件\n\n15套配色含中国红等本地化方案\n单文件输出，浏览器直接打开",
  },
  {
    slug: "code-review", name: "代码审查", nameEn: "code-review", type: "enhanced", category: "开发工具",
    lines: 283, safetyScore: 90, grade: "A",
    installCmd: "npx skills add mindverse/skillhub@code-review -g -y",
    description: "AI 代码质量守护者。结构化审查报告，覆盖安全漏洞、性能优化、最佳实践，支持10种编程语言。",
    features: ["严重/警告/建议三级", "10种语言审查", "安全漏洞检查", "性能优化建议", "最佳实践推荐"],
    useCases: ["帮我review代码", "这段代码有问题吗", "PR审查", "代码质量检查"],
    triggerWords: ["代码审查", "code review", "PR review", "帮我review"],
    skillMdPreview: "# 代码审查 — AI 代码质量守护者\n\n## 五阶段工作流\n1. 理解上下文\n2. 逐文件审查\n3. 安全检查\n4. 性能检查\n5. 汇总报告（严重/警告/建议三级）",
  },
  {
    slug: "security-audit", name: "安全审计", nameEn: "security-audit", type: "enhanced", category: "安全",
    lines: 477, safetyScore: 92, grade: "S",
    installCmd: "npx skills add mindverse/skillhub@security-audit -g -y",
    description: "AI 安全审计专家。OWASP Top 10:2025 逐项检查，依赖漏洞扫描，敏感信息检测，输出含 CWE 编号的修复建议。",
    features: ["OWASP Top 10:2025", "依赖安全扫描", "敏感信息检测", "CWE编号", "A-F安全评级", "9种语言安全陷阱"],
    useCases: ["安全审计一下", "有没有漏洞", "OWASP检查", "敏感信息泄露"],
    triggerWords: ["安全审计", "漏洞扫描", "security audit", "OWASP"],
    skillMdPreview: "# 安全审计 — OWASP Top 10 专家\n\n## 五阶段工作流\n1. 确定审计范围\n2. OWASP Top 10 逐项检查（含不安全/安全代码对比）\n3. 依赖安全扫描\n4. 敏感信息检测\n5. 输出报告（高危/中危/低危 + CWE + 修复代码）",
  },
  {
    slug: "react-best-practices", name: "React宝典", nameEn: "react-best-practices", type: "enhanced", category: "开发工具",
    lines: 929, safetyScore: 90, grade: "A", upstream: "vercel-labs/agent-skills",
    installCmd: "npx skills add mindverse/skillhub@react-best-practices -g -y",
    description: "React 19+ / Next.js 15+ 最佳实践指南，929行10个章节。覆盖性能优化、Server Components、Hooks、状态管理。",
    features: ["React 19+ 新API", "Server Components", "Bundle优化", "重渲染优化", "Next.js 15+", "PPR/缓存策略"],
    useCases: ["React怎么写最好", "性能优化", "Server Components怎么用", "Next.js最佳实践"],
    triggerWords: ["React", "Next.js", "最佳实践", "hooks", "Server Components"],
    skillMdPreview: "# React宝典 — 最佳实践指南\n\n基于 Vercel react-best-practices（17.6万安装）增强。\n\n## 十大章节\n1. 消除请求瀑布 [CRITICAL]\n2. Bundle体积优化 [CRITICAL]\n3. 服务端性能\n4. 客户端数据获取\n5. 重渲染优化\n6. 渲染性能\n7. JavaScript性能\n8. 高级模式\n9. React 19+ 新特性\n10. Server Components & Next.js 15+",
  },
  {
    slug: "douyin-script", name: "抖音脚本", nameEn: "douyin-script", type: "original", category: "内容创作",
    lines: 280, safetyScore: 85, grade: "A",
    installCmd: "npx skills add mindverse/skillhub@douyin-script -g -y",
    description: "抖音短视频脚本创作助手，支持口播、带货、剧情、分镜、Vlog 五种类型。前3秒是生死线。",
    features: ["5种脚本类型", "3秒钩子公式", "分镜表输出", "带货话术", "评论区引导"],
    useCases: ["写个抖音脚本", "带货视频怎么写", "拍摄分镜", "口播稿"],
    triggerWords: ["抖音", "短视频", "脚本", "分镜", "带货", "口播", "douyin"],
    skillMdPreview: "# 抖音脚本 — 短视频创作\n\n## 五种脚本类型\n口播 / 带货 / 剧情 / 分镜 / Vlog\n\n## 工作流\n1. 理解需求\n2. 确定类型\n3. 写钩子开头（3秒抓注意力）\n4. 撰写正文\n5. 写结尾引导\n6. 生成分镜表（画面|台词|时长|备注）",
  },
  {
    slug: "wechat-mp", name: "公众号", nameEn: "wechat-mp", type: "original", category: "内容创作",
    lines: 260, safetyScore: 85, grade: "A",
    installCmd: "npx skills add mindverse/skillhub@wechat-mp -g -y",
    description: "微信公众号文章撰写助手，支持深度分析、干货教程、故事型、观点评论、轻松生活五种风格。",
    features: ["5种文章风格", "标题优化（5个备选）", "摘要生成", "手机端排版", "关注/转发引导"],
    useCases: ["写公众号文章", "帮我写推文", "公众号标题优化", "排版一下"],
    triggerWords: ["公众号", "微信推文", "公众号文章", "wechat"],
    skillMdPreview: "# 公众号 — 微信文章助手\n\n## 五种风格\n严肃深度 / 轻松幽默 / 故事型 / 干货型 / 新闻评论\n\n## 公众号特点\n标题党但不低俗 / 段落短适配手机 / 加粗关键句 / 引用格式 / 分割线 / 首图描述建议",
  },
  {
    slug: "tdd", name: "测试驱动", nameEn: "tdd", type: "enhanced", category: "开发工具",
    lines: 200, safetyScore: 88, grade: "A",
    installCmd: "npx skills add mindverse/skillhub@tdd -g -y",
    description: "测试驱动开发助手，红-绿-重构工作流，支持 Jest/Vitest/pytest 等主流测试框架。",
    features: ["红绿重构", "Jest/Vitest/pytest", "覆盖率优化", "测试策略设计"],
    useCases: ["TDD开发", "写测试", "测试驱动", "提高覆盖率"],
    triggerWords: ["TDD", "测试驱动", "写测试", "单元测试"],
    skillMdPreview: "# 测试驱动 — TDD 工作流\n\n红→绿→重构循环\n支持 Jest / Vitest / pytest / Go testing",
  },
  {
    slug: "debugger", name: "快速调试", nameEn: "debugger", type: "enhanced", category: "开发工具",
    lines: 200, safetyScore: 88, grade: "A",
    installCmd: "npx skills add mindverse/skillhub@debugger -g -y",
    description: "快速定位和修复 bug，结构化调试流程：复现→缩小→定位→修复→验证。",
    features: ["结构化调试流程", "日志分析", "堆栈追踪", "二分法定位"],
    useCases: ["帮我调试", "这个bug怎么修", "报错了怎么办", "快速定位问题"],
    triggerWords: ["调试", "debug", "报错", "bug", "定位问题"],
    skillMdPreview: "# 快速调试\n\n复现→缩小范围→定位根因→修复→验证",
  },
  {
    slug: "project-planner", name: "项目规划", nameEn: "project-planner", type: "enhanced", category: "效率工具",
    lines: 200, safetyScore: 88, grade: "A",
    installCmd: "npx skills add mindverse/skillhub@project-planner -g -y",
    description: "技术项目拆解和规划，从需求分析到排期。",
    features: ["需求分析", "技术选型", "模块拆解", "里程碑规划"],
    useCases: ["项目怎么规划", "帮我拆解任务", "技术方案", "排期"],
    triggerWords: ["项目规划", "任务拆解", "排期", "技术方案"],
    skillMdPreview: "# 项目规划\n\n需求分析→技术选型→模块拆解→里程碑→排期",
  },
  {
    slug: "seo-master", name: "SEO大师", nameEn: "seo-master", type: "enhanced", category: "营销",
    lines: 200, safetyScore: 88, grade: "A",
    installCmd: "npx skills add mindverse/skillhub@seo-master -g -y",
    description: "网站 SEO 优化，覆盖技术SEO、内容优化、结构化数据、Core Web Vitals。",
    features: ["Core Web Vitals", "结构化数据", "sitemap", "关键词优化"],
    useCases: ["SEO优化", "提升排名", "网站流量", "关键词分析"],
    triggerWords: ["SEO", "搜索优化", "排名", "流量"],
    skillMdPreview: "# SEO大师\n\n技术SEO / 内容优化 / 结构化数据 / Core Web Vitals / sitemap",
  },
  {
    slug: "copywriter", name: "文案大师", nameEn: "copywriter", type: "enhanced", category: "内容创作",
    lines: 200, safetyScore: 88, grade: "A",
    installCmd: "npx skills add mindverse/skillhub@copywriter -g -y",
    description: "各类营销文案撰写，广告/着陆页/邮件/社交媒体/品牌故事。",
    features: ["广告文案", "着陆页", "邮件营销", "品牌故事"],
    useCases: ["写广告文案", "着陆页文案", "邮件营销", "品牌故事"],
    triggerWords: ["文案", "广告", "营销", "着陆页", "copywriting"],
    skillMdPreview: "# 文案大师\n\n广告文案 / 着陆页 / 邮件营销 / 社交媒体 / 品牌故事",
  },
  {
    slug: "data-analyst", name: "数据分析", nameEn: "data-analyst", type: "enhanced", category: "数据",
    lines: 200, safetyScore: 88, grade: "A",
    installCmd: "npx skills add mindverse/skillhub@data-analyst -g -y",
    description: "数据分析助手，CSV/JSON 分析、统计摘要、趋势分析、可视化建议。",
    features: ["CSV/JSON分析", "统计摘要", "趋势分析", "可视化建议"],
    useCases: ["分析这个数据", "CSV分析", "趋势是什么", "数据可视化"],
    triggerWords: ["数据分析", "CSV", "统计", "趋势", "data analysis"],
    skillMdPreview: "# 数据分析\n\nCSV/JSON分析 / 统计摘要 / 趋势分析 / 可视化建议",
  },
  {
    slug: "api-builder", name: "接口构建", nameEn: "api-builder", type: "enhanced", category: "开发工具",
    lines: 200, safetyScore: 88, grade: "A",
    installCmd: "npx skills add mindverse/skillhub@api-builder -g -y",
    description: "REST/GraphQL API 设计和构建，路由设计、数据模型、认证、文档生成。",
    features: ["路由设计", "数据模型", "认证授权", "API文档生成"],
    useCases: ["设计API", "接口怎么写", "REST API", "GraphQL"],
    triggerWords: ["API", "接口", "REST", "GraphQL", "路由"],
    skillMdPreview: "# 接口构建\n\n路由设计 / 数据模型 / 认证 / 文档生成 / 错误处理",
  },
  {
    slug: "git-master", name: "Git大师", nameEn: "git-master", type: "enhanced", category: "开发工具",
    lines: 200, safetyScore: 88, grade: "A",
    installCmd: "npx skills add mindverse/skillhub@git-master -g -y",
    description: "Git 操作指导，分支策略、合并冲突解决、rebase、提交规范。",
    features: ["分支策略", "合并冲突", "rebase", "git hooks", "提交规范"],
    useCases: ["合并冲突怎么解决", "分支策略", "git rebase", "提交规范"],
    triggerWords: ["Git", "分支", "合并", "rebase", "提交"],
    skillMdPreview: "# Git大师\n\n分支策略 / 合并冲突 / rebase / cherry-pick / git hooks / 提交规范",
  },
  {
    slug: "zhihu-writer", name: "知乎回答", nameEn: "zhihu-writer", type: "original", category: "内容创作",
    lines: 200, safetyScore: 88, grade: "A",
    installCmd: "npx skills add mindverse/skillhub@zhihu-writer -g -y",
    description: "知乎风格长文回答，开头先下结论，逻辑严密，引用数据，专业但不枯燥。",
    features: ["先下结论", "逻辑严密", "引用数据", "专业不枯燥"],
    useCases: ["写知乎回答", "长文分析", "深度解读", "专业回答"],
    triggerWords: ["知乎", "回答", "长文", "深度分析"],
    skillMdPreview: "# 知乎回答\n\n开头先下结论 / 逻辑严密 / 引用数据 / 专业但不枯燥 / 段落分明",
  },
  {
    slug: "bilibili-script", name: "B站文案", nameEn: "bilibili-script", type: "original", category: "内容创作",
    lines: 200, safetyScore: 88, grade: "A",
    installCmd: "npx skills add mindverse/skillhub@bilibili-script -g -y",
    description: "B站视频文案和脚本，年轻化语言、弹幕友好、三连引导。",
    features: ["年轻化语言", "弹幕友好", "三连引导", "知识/生活/测评"],
    useCases: ["B站视频文案", "视频脚本", "弹幕互动", "三连引导"],
    triggerWords: ["B站", "bilibili", "弹幕", "视频文案", "三连"],
    skillMdPreview: "# B站文案\n\n年轻化语言 / 弹幕友好 / 三连引导 / 知识类 / 生活类 / 测评类",
  },
  // ===== Batch 4: 补分类 + 原创 =====
  { slug: "docker-deploy", name: "Docker部署", nameEn: "docker-deploy", type: "enhanced", category: "运维", lines: 220, safetyScore: 88, grade: "A", installCmd: "npx skills add mindverse/skillhub@docker-deploy -g -y", description: "Docker 部署与容器化，Dockerfile/docker-compose/多阶段构建/安全加固。", features: ["Dockerfile", "docker-compose", "多阶段构建", "安全加固"], useCases: ["Docker 部署", "容器化应用", "写 Dockerfile"], triggerWords: ["Docker", "容器", "部署", "Dockerfile"], skillMdPreview: "# Docker部署\n\nDockerfile / docker-compose / 多阶段构建 / 安全加固" },
  { slug: "ci-cd", name: "CI/CD流水线", nameEn: "ci-cd", type: "enhanced", category: "运维", lines: 220, safetyScore: 88, grade: "A", installCmd: "npx skills add mindverse/skillhub@ci-cd -g -y", description: "CI/CD 流水线配置，GitHub Actions/GitLab CI/缓存策略。", features: ["GitHub Actions", "GitLab CI", "缓存策略", "安全措施"], useCases: ["配置 CI/CD", "GitHub Actions", "自动化部署"], triggerWords: ["CI/CD", "GitHub Actions", "流水线", "自动化部署"], skillMdPreview: "# CI/CD流水线\n\nGitHub Actions / GitLab CI / 缓存 / 安全" },
  { slug: "slack-bot", name: "Slack集成", nameEn: "slack-bot", type: "enhanced", category: "集成", lines: 200, safetyScore: 88, grade: "A", installCmd: "npx skills add mindverse/skillhub@slack-bot -g -y", description: "Slack Bot 开发，Webhook/Slash Command/Block Kit/OAuth。", features: ["Bot 开发", "Webhook", "Slash Command", "Block Kit"], useCases: ["做 Slack Bot", "Slack 集成", "消息通知"], triggerWords: ["Slack", "Bot", "Webhook"], skillMdPreview: "# Slack集成\n\nBot / Webhook / Slash Command / Block Kit / OAuth" },
  { slug: "tutorial-writer", name: "教程编写", nameEn: "tutorial-writer", type: "enhanced", category: "教育", lines: 200, safetyScore: 88, grade: "A", installCmd: "npx skills add mindverse/skillhub@tutorial-writer -g -y", description: "技术教程编写，课程大纲、学习路线、实战项目。", features: ["入门教程", "实战项目", "课程大纲", "学习路线"], useCases: ["写教程", "课程大纲", "学习路线"], triggerWords: ["教程", "课程", "学习路线", "tutorial"], skillMdPreview: "# 教程编写\n\n入门教程 / 实战项目 / 课程大纲 / 学习路线" },
  { slug: "video-editor", name: "视频脚本", nameEn: "video-editor", type: "enhanced", category: "多媒体", lines: 200, safetyScore: 88, grade: "A", installCmd: "npx skills add mindverse/skillhub@video-editor -g -y", description: "通用视频脚本、分镜表、SRT字幕。", features: ["宣传片", "教学视频", "分镜表", "SRT字幕"], useCases: ["写视频脚本", "分镜设计", "字幕生成"], triggerWords: ["视频脚本", "分镜", "字幕"], skillMdPreview: "# 视频脚本\n\n宣传片 / 教学 / 广告 / 分镜表 / SRT字幕" },
  { slug: "email-marketing", name: "邮件营销", nameEn: "email-marketing", type: "enhanced", category: "营销", lines: 200, safetyScore: 88, grade: "A", installCmd: "npx skills add mindverse/skillhub@email-marketing -g -y", description: "Newsletter/营销推广/邮件序列/冷邮件。", features: ["Newsletter", "邮件序列", "冷邮件", "事务性邮件"], useCases: ["写营销邮件", "Newsletter", "邮件序列"], triggerWords: ["邮件", "Newsletter", "email marketing"], skillMdPreview: "# 邮件营销\n\nNewsletter / 营销 / 邮件序列 / 冷邮件" },
  { slug: "weibo-hot", name: "微博热搜", nameEn: "weibo-hot", type: "original", category: "内容创作", lines: 200, safetyScore: 88, grade: "A", installCmd: "npx skills add mindverse/skillhub@weibo-hot -g -y", description: "微博热搜风格文案，话题分析，品牌蓝V运营。", features: ["热搜体写作", "品牌蓝V", "话题分析", "评论互动"], useCases: ["微博文案", "热搜分析", "蓝V运营"], triggerWords: ["微博", "热搜", "蓝V"], skillMdPreview: "# 微博热搜\n\n热搜体 / 品牌蓝V / 话题分析 / 评论互动" },
  { slug: "taobao-listing", name: "淘宝详情", nameEn: "taobao-listing", type: "original", category: "内容创作", lines: 200, safetyScore: 88, grade: "A", installCmd: "npx skills add mindverse/skillhub@taobao-listing -g -y", description: "淘宝详情页文案，FAB卖点提炼，广告法合规。", features: ["商品标题SEO", "FAB卖点", "详情页逻辑", "广告法合规"], useCases: ["淘宝详情页", "商品文案", "卖点提炼"], triggerWords: ["淘宝", "详情页", "商品文案", "卖点"], skillMdPreview: "# 淘宝详情\n\n商品标题SEO / FAB卖点 / 详情页 / 广告法合规" },
  { slug: "resume-zh", name: "中文简历", nameEn: "resume-zh", type: "original", category: "效率工具", lines: 200, safetyScore: 88, grade: "A", installCmd: "npx skills add mindverse/skillhub@resume-zh -g -y", description: "中文简历、求职信、自我介绍，STAR法则。", features: ["应届/社招/转行", "STAR法则", "求职信", "简历评分"], useCases: ["写简历", "求职信", "自我介绍"], triggerWords: ["简历", "求职", "自我介绍", "resume"], skillMdPreview: "# 中文简历\n\n应届/社招/转行 / STAR法则 / 求职信 / 简历评分" },
  { slug: "meeting-notes", name: "会议纪要", nameEn: "meeting-notes", type: "original", category: "效率工具", lines: 200, safetyScore: 88, grade: "A", installCmd: "npx skills add mindverse/skillhub@meeting-notes -g -y", description: "会议纪要整理、待办提取、跟进邮件。", features: ["站会/周会/复盘", "待办提取", "跟进邮件", "录音整理"], useCases: ["整理会议纪要", "提取待办", "写跟进邮件"], triggerWords: ["会议", "纪要", "待办", "meeting notes"], skillMdPreview: "# 会议纪要\n\n站会/周会/复盘 / 待办提取 / 跟进邮件" },
  // ===== Batch 5: 更多原创 + 通用 =====
  { slug: "weekly-report", name: "周报生成器", nameEn: "weekly-report", type: "original", category: "效率工具", lines: 200, safetyScore: 88, grade: "A", installCmd: "npx skills add mindverse/skillhub@weekly-report -g -y", description: "从 git log/任务列表生成周报，STAR格式，量化成果。", features: ["git log 提炼", "STAR格式", "量化成果", "多岗位"], useCases: ["写周报", "日报", "月报"], triggerWords: ["周报", "日报", "月报", "工作总结"], skillMdPreview: "# 周报生成器\n\ngit log 提炼 / STAR格式 / 量化成果" },
  { slug: "interviewer", name: "面试官", nameEn: "interviewer", type: "original", category: "效率工具", lines: 200, safetyScore: 88, grade: "A", installCmd: "npx skills add mindverse/skillhub@interviewer -g -y", description: "模拟技术面试，前端/后端/算法/系统设计，追问+评分。", features: ["前端/后端/算法", "由浅入深追问", "即时评分", "面试报告"], useCases: ["模拟面试", "技术面试", "面试准备"], triggerWords: ["面试", "模拟面试", "interview"], skillMdPreview: "# 面试官\n\n前端/后端/算法/系统设计 / 追问 / 评分 / 面试报告" },
  { slug: "contract-review", name: "合同审查", nameEn: "contract-review", type: "original", category: "效率工具", lines: 200, safetyScore: 88, grade: "A", installCmd: "npx skills add mindverse/skillhub@contract-review -g -y", description: "合同条款风险审查，霸王条款标注，中国法律场景。", features: ["劳动/租房/合作合同", "风险分级", "霸王条款", "中国法律"], useCases: ["审查合同", "看看合同有没有坑", "合同风险"], triggerWords: ["合同", "审查", "霸王条款", "法律"], skillMdPreview: "# 合同审查\n\n劳动/租房/合作/NDA / 风险分级 / 中国法律" },
  { slug: "wechat-mini", name: "微信小程序", nameEn: "wechat-mini", type: "original", category: "开发工具", lines: 250, safetyScore: 88, grade: "A", installCmd: "npx skills add mindverse/skillhub@wechat-mini -g -y", description: "微信小程序开发，WXML/WXSS/JS 代码生成，云开发。", features: ["WXML/WXSS/JS", "云开发", "支付/登录", "Taro/uni-app"], useCases: ["开发小程序", "微信小程序", "小程序代码"], triggerWords: ["小程序", "微信小程序", "wechat mini"], skillMdPreview: "# 微信小程序\n\nWXML/WXSS/JS / 云开发 / 支付 / 登录 / Taro" },
  { slug: "podcast-script", name: "播客脚本", nameEn: "podcast-script", type: "original", category: "内容创作", lines: 200, safetyScore: 88, grade: "A", installCmd: "npx skills add mindverse/skillhub@podcast-script -g -y", description: "中文播客脚本，单口/对谈/访谈，时间轴规划。", features: ["单口/对谈/访谈", "时间轴", "口语化", "Shownotes"], useCases: ["写播客脚本", "播客大纲", "访谈提纲"], triggerWords: ["播客", "podcast", "访谈", "对谈"], skillMdPreview: "# 播客脚本\n\n单口/对谈/访谈 / 时间轴 / 口语化 / Shownotes" },
  { slug: "gaokao-essay", name: "高考作文", nameEn: "gaokao-essay", type: "original", category: "教育", lines: 200, safetyScore: 88, grade: "A", installCmd: "npx skills add mindverse/skillhub@gaokao-essay -g -y", description: "高考风格议论文/记叙文，审题立意，素材库。", features: ["议论文/记叙文", "审题立意", "素材库", "作文评分"], useCases: ["高考作文", "议论文", "作文辅导"], triggerWords: ["高考", "作文", "议论文", "记叙文"], skillMdPreview: "# 高考作文\n\n议论文/记叙文 / 审题立意 / 素材库 / 作文评分" },
  { slug: "sql-helper", name: "SQL助手", nameEn: "sql-helper", type: "enhanced", category: "开发工具", lines: 200, safetyScore: 88, grade: "A", installCmd: "npx skills add mindverse/skillhub@sql-helper -g -y", description: "SQL 编写/优化/建表，MySQL/PostgreSQL/SQLite。", features: ["SQL编写", "查询优化", "索引建议", "多数据库"], useCases: ["写 SQL", "优化查询", "建表"], triggerWords: ["SQL", "MySQL", "PostgreSQL", "数据库查询"], skillMdPreview: "# SQL助手\n\nMySQL / PostgreSQL / SQLite / 索引优化" },
  { slug: "regex-helper", name: "正则大师", nameEn: "regex-helper", type: "enhanced", category: "开发工具", lines: 200, safetyScore: 88, grade: "A", installCmd: "npx skills add mindverse/skillhub@regex-helper -g -y", description: "正则表达式编写、解释、调试，逐段拆解。", features: ["正则编写", "逐段解释", "多语言差异", "常用速查"], useCases: ["写正则", "解释正则", "正则调试"], triggerWords: ["正则", "regex", "正则表达式"], skillMdPreview: "# 正则大师\n\n编写 / 解释 / 调试 / 多语言差异 / 速查库" },
  { slug: "markdown-doc", name: "文档大师", nameEn: "markdown-doc", type: "enhanced", category: "开发工具", lines: 200, safetyScore: 88, grade: "A", installCmd: "npx skills add mindverse/skillhub@markdown-doc -g -y", description: "README/API文档/技术文档/Changelog 编写。", features: ["README", "API文档", "Changelog", "贡献指南"], useCases: ["写 README", "API 文档", "Changelog"], triggerWords: ["文档", "README", "API文档", "Changelog"], skillMdPreview: "# 文档大师\n\nREADME / API文档 / 架构文档 / Changelog / 贡献指南" },
  { slug: "performance-tuner", name: "性能调优", nameEn: "performance-tuner", type: "enhanced", category: "开发工具", lines: 200, safetyScore: 88, grade: "A", installCmd: "npx skills add mindverse/skillhub@performance-tuner -g -y", description: "Web 性能优化，Core Web Vitals/Lighthouse/打包优化。", features: ["Core Web Vitals", "Lighthouse", "打包优化", "缓存策略"], useCases: ["性能优化", "Lighthouse 分析", "打包体积"], triggerWords: ["性能", "优化", "Lighthouse", "Core Web Vitals"], skillMdPreview: "# 性能调优\n\nCore Web Vitals / Lighthouse / 打包 / 缓存" },
  // ===== Batch 6: 冲 50 =====
  { slug: "paper-reducer", name: "论文降重", nameEn: "paper-reducer", type: "original", category: "教育", lines: 200, safetyScore: 88, grade: "A", installCmd: "npx skills add mindverse/skillhub@paper-reducer -g -y", description: "论文查重率降低，同义替换、句式改写、段落重组。", features: ["同义替换", "句式改写", "段落重组", "学术规范"], useCases: ["论文降重", "降低查重率", "改写论文"], triggerWords: ["论文", "降重", "查重", "改写"], skillMdPreview: "# 论文降重\n\n同义替换 / 句式改写 / 段落重组" },
  { slug: "naming-master", name: "取名大师", nameEn: "naming-master", type: "original", category: "效率工具", lines: 200, safetyScore: 88, grade: "A", installCmd: "npx skills add mindverse/skillhub@naming-master -g -y", description: "品牌/产品/公司/App 起名，中英文命名+寓意分析。", features: ["中英文命名", "域名检查", "寓意分析", "商标建议"], useCases: ["起名字", "品牌命名", "产品名"], triggerWords: ["起名", "命名", "取名", "品牌名"], skillMdPreview: "# 取名大师\n\n中英文命名 / 域名检查 / 寓意分析" },
  { slug: "dingding-doc", name: "钉钉文档", nameEn: "dingding-doc", type: "original", category: "效率工具", lines: 200, safetyScore: 88, grade: "A", installCmd: "npx skills add mindverse/skillhub@dingding-doc -g -y", description: "钉钉文档、OKR、审批流程。", features: ["钉钉文档", "OKR", "审批流程", "钉钉格式"], useCases: ["钉钉文档", "写 OKR", "审批流程"], triggerWords: ["钉钉", "DingTalk", "OKR"], skillMdPreview: "# 钉钉文档\n\n钉钉文档 / OKR / 审批流程" },
  { slug: "redbook-analytics", name: "小红书数据", nameEn: "redbook-analytics", type: "original", category: "数据", lines: 200, safetyScore: 88, grade: "A", installCmd: "npx skills add mindverse/skillhub@redbook-analytics -g -y", description: "小红书账号数据分析，爆文规律，标签策略优化。", features: ["账号分析", "爆文规律", "标签策略", "发布时间"], useCases: ["小红书数据分析", "爆文分析", "账号诊断"], triggerWords: ["小红书数据", "爆文", "账号分析"], skillMdPreview: "# 小红书数据\n\n账号分析 / 爆文规律 / 标签策略 / 发布时间" },
  { slug: "chinese-copyfix", name: "去AI味", nameEn: "chinese-copyfix", type: "original", category: "内容创作", lines: 200, safetyScore: 88, grade: "A", installCmd: "npx skills add mindverse/skillhub@chinese-copyfix -g -y", description: "把 AI 生成的中文改写成人话，去掉套路化表达。", features: ["去AI痕迹", "加个人风格", "口语化", "真实感"], useCases: ["去AI味", "改写成人话", "让文案更真实"], triggerWords: ["去AI味", "像人写的", "改写", "人话"], skillMdPreview: "# 去AI味\n\n去AI痕迹 / 加个人风格 / 口语化 / 真实感" },
  { slug: "aws-helper", name: "AWS助手", nameEn: "aws-helper", type: "enhanced", category: "运维", lines: 200, safetyScore: 88, grade: "A", installCmd: "npx skills add mindverse/skillhub@aws-helper -g -y", description: "AWS 服务配置，S3/EC2/Lambda/CloudFormation/IAM。", features: ["S3/EC2/Lambda", "CloudFormation", "IAM策略", "成本优化"], useCases: ["AWS 配置", "Lambda 函数", "IAM 策略"], triggerWords: ["AWS", "S3", "Lambda", "CloudFormation"], skillMdPreview: "# AWS助手\n\nS3 / EC2 / Lambda / CloudFormation / IAM" },
  { slug: "typescript-strict", name: "TypeScript", nameEn: "typescript-strict", type: "enhanced", category: "开发工具", lines: 200, safetyScore: 88, grade: "A", installCmd: "npx skills add mindverse/skillhub@typescript-strict -g -y", description: "严格类型 TypeScript，泛型、类型体操、类型守卫。", features: ["严格模式", "泛型", "类型体操", "类型守卫"], useCases: ["TypeScript 类型", "泛型怎么写", "类型体操"], triggerWords: ["TypeScript", "TS类型", "泛型", "类型体操"], skillMdPreview: "# TypeScript\n\n严格模式 / 泛型 / 类型体操 / 类型守卫" },
  { slug: "landing-page", name: "着陆页", nameEn: "landing-page", type: "enhanced", category: "设计", lines: 200, safetyScore: 88, grade: "A", installCmd: "npx skills add mindverse/skillhub@landing-page -g -y", description: "高转化率着陆页设计与开发，Hero/CTA/社会证明。", features: ["Hero区域", "CTA优化", "社会证明", "移动优先"], useCases: ["做着陆页", "landing page", "产品页面"], triggerWords: ["着陆页", "landing page", "首页", "转化率"], skillMdPreview: "# 着陆页\n\nHero / CTA / 社会证明 / FAQ / 移动优先" },
  { slug: "chrome-extension", name: "浏览器插件", nameEn: "chrome-extension", type: "enhanced", category: "开发工具", lines: 200, safetyScore: 88, grade: "A", installCmd: "npx skills add mindverse/skillhub@chrome-extension -g -y", description: "Chrome Extension 开发，Manifest V3，content script。", features: ["Manifest V3", "content script", "popup", "storage API"], useCases: ["开发浏览器插件", "Chrome 扩展", "content script"], triggerWords: ["Chrome扩展", "浏览器插件", "extension"], skillMdPreview: "# 浏览器插件\n\nManifest V3 / content script / popup / storage" },
  { slug: "system-design", name: "系统设计", nameEn: "system-design", type: "enhanced", category: "开发工具", lines: 200, safetyScore: 88, grade: "A", installCmd: "npx skills add mindverse/skillhub@system-design -g -y", description: "面试级系统设计，高并发、分布式、缓存、消息队列。", features: ["容量估算", "高层设计", "数据库选型", "Trade-offs"], useCases: ["系统设计", "架构设计", "面试准备"], triggerWords: ["系统设计", "架构", "高并发", "system design"], skillMdPreview: "# 系统设计\n\n容量估算 / 高层设计 / 深入设计 / 扩展优化 / Trade-offs" },
];
